export const SET_USER_LOGIN = 'SET_USER_LOGIN'
export const SET_CLIENT_VIEWPORT = 'SET_CLIENT_VIEWPORT'

export const SET_PLAYING_STATE = 'SET_PLAYING_STATE'
export const SET_FULL_SCREEN = 'SET_FULL_SCREEN'
export const SET_PLAYLIST = 'SET_PLAYLIST'
export const SET_SEQUENCE_LIST = 'SET_SEQUENCE_LIST'
export const SET_PLAY_MODE = 'SET_PLAY_MODE'
export const SET_CURRENT_INDEX = 'SET_CURRENT_INDEX'
export const SET_PLAY_TYPE = 'SET_PLAY_TYPE'
export const SET_REC_MODE = 'SET_REC_MODE'

export const ADD_SEARCH_HISTORY = 'ADD_SEARCH_HISTORY'
export const CLEAR_SEARCH_HISTORY = 'CLEAR_SEARCH_HISTORY'
export const DEL_SEARCH_HISTORY_FOR_INDEX = 'DEL_SEARCH_HISTORY_FOR_INDEX'

export const SET_PLAY_HISTORY = 'SET_PLAY_HISTORY'